name: Build Base Images
on:
  schedule:
    - cron: "0 */72 * * *"
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.1]

    name: P${{ matrix.php }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Images
        uses: docker/build-push-action@v4
        with:
          context: ./src
          platforms: linux/amd64,linux/arm64
          build-args: PHP_VERSION=${{ matrix.php }}
          push: true
          tags: oliverds/fly-laravel:${{ matrix.php }}
